### ISSUE TITLE
Need example calibration file

### ISSUE THREAD

**Issue by dguest** [Marie89/ATHENA-retagging-setup#3]
Maybe add a `data/` directory that contains an example json file for `DL1Tag` to read in. It's a bit ugly to upload a lot of configuration to github, but the general configuration should be relatively stable, and it would be nice to have _something_ for runtests.

**Comment by malanfer** [comment]
A json file that can be used for testing is already available by the hardcoded path to a public directory (i.e. `/afs/cern.ch/user/m/malanfer/public/training_files/AGILEPack_b-tagging.weights.json` in `DL1Tag.cxx` in `JetTagTools`). Going to close this pull request now.
